package com.intellij.graphql.javascript.workspace

import com.intellij.workspaceModel.core.fileIndex.impl.ModuleOrLibrarySourceRootData

internal class GraphQLSourceRootFileSetData : ModuleOrLibrarySourceRootData